// General
export const LOGIN_START = 'LOGIN_START';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const SET_CURRENT_PAGE = 'SET_CURRENT_PAGE';
export const SET_LANGUAGE = 'SET_LANGUAGE';
export const SET_SESSION_ID = 'SET_SESSION_ID';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';
export const FETCH_EMPLOYEES_DATA_START= 'FETCH_EMPLOYEES_DATA_START';
export const FETCH_EMPLOYEES_DATA_SUCCESS= 'FETCH_EMPLOYEES_DATA_SUCCESS';
export const FETCH_EMPLOYEES_DATA_FAIL= 'FETCH_EMPLOYEES_DATA_FAIL';
export const SET_EMPLOYEES_PAGER = 'SET_EMPLOYEES_PAGER';
export const GET_CURRENT_USER_START = 'GET_CURRENT_USER_START';
export const GET_CURRENT_USER_SUCCESS = 'GET_CURRENT_USER_SUCCESS';
export const GET_CURRENT_USER_FAIL= 'GET_CURRENT_USER_FAIL';
export const AUTH_CHECK_TIMEOUT = 'AUTH_CHECK_TIMEOUT'
export const GET_STATION_ID_SUCCESS = 'GET_STATION_ID_SUCCESS'
export const GET_PERMISSIONS_START = 'GET_PERMISSIONS_START'
export const GET_PERMISSIONS_SUCCESS = 'GET_PERMISSIONS_SUCCESS'
export const GET_PERMISSIONS_FAIL = 'GET_PERMISSIONS_FAIL'

// General sagas;   
export const AUTH_CHECK_STATE = 'AUTH_CHECK_STATE';
export const LOGIN_USER = 'LOGIN_USER';
export const AUTH_INITIATE_LOGOUT = 'AUTH_INITIATE_LOGOUT';
export const FETCH_EMPLOYEES_DATA = 'FETCH_EMPLOYEES_DATA'
export const GET_CURRENT_USER = 'GET_CURRENT_USER';
export const GET_STATION_ID = 'GET_STATION_ID'
export const GET_PERMISSIONS = 'GET_PERMISSIONS'

// Actual Punches
export const FETCH_ACTUAL_PUNCHES_START = 'FETCH_ACTUAL_PUNCHES_START';
export const FETCH_ACTUAL_PUNCHES_SUCCESS = 'FETCH_ACTUAL_PUNCHES_SUCCESS';
export const FETCH_ACTUAL_PUNCHES_FAIL = 'FETCH_ACTUAL_PUNCHES_FAIL';
export const GET_GENERIC_DATA_START = 'GET_GENERIC_DATA_START';
export const GET_GENERIC_DATA_SUCCESS = 'GET_GENERIC_DATA_SUCCESS';
export const GET_GENERIC_DATA_FAIL = 'GET_GENERIC_DATA_FAIL';
export const SET_GENERIC_DATA_ACTUAL_PUNCHES_SUCCESS = 'SET_GENERIC_DATA_ACTUAL_PUNCHES_SUCCESS';
export const SET_GENERIC_DATA_ACTUAL_PUNCHES_FAIL = 'SET_GENERIC_DATA_ACTUAL_PUNCHES_FAIL';
export const SET_REQUEST_ACTUAL_PUNCHES_DATA = 'SET_REQUEST_ACTUAL_PUNCHES_DATA';
export const EXPORT_ACTUAL_PUNCH_SUCCESS = 'EXPORT_ACTUAL_PUNCH_SUCCESS';
export const CHANGE_PAGE_NUMBER_ACTUAL_PUNCH = 'CHANGE_PAGE_NUMBER_ACTUAL_PUNCH';
export const SET_PAGER_DATA_ACTUAL_PUNCH  = 'SET_PAGER_DATA_ACTUAL_PUNCH';
export const REFRESH_LOADING  = 'REFRESH_LOADING';
export const SORT_ACTUAL_PUNCHES = 'SORT_ACTUAL_PUNCHES';
export const CHANGE_FILTER_DATA_ACTUAL_PUNCHES = 'CHANGE_FILTER_DATA_ACTUAL_PUNCHES';
export const REDIRECT_ACTUAL_PUNCHES = 'REDIRECT_ACTUAL_PUNCHES';
// Actual Punches Sagas
export const GENERIC_DATA_ACTUAL_PUNCHES = 'GENERIC_DATA_ACTUAL_PUNCHES';
export const FETCH_ACTUAL_PUNCHES = 'FETCH_ACTUAL_PUNCHES';
export const EXPORT_ACTUAL_PUNCH = 'EXPORT_ACTUAL_PUNCH';
export const SET_GENERIC_DATA_ACTUAL_PUNCHES = 'SET_GENERIC_DATA_ACTUAL_PUNCHES';

// Accrual Balances
export const GET_GENERIC_ACCRUAL_BALANCES_DATA_START = 'GET_GENERIC_ACCRUAL_BALANCES_DATA_START';
export const GET_GENERIC_DATA_ACCRUAL_BALANCES_SUCCESS = 'GET_GENERIC_DATA_ACCRUAL_BALANCES_SUCCESS';
export const GET_GENERIC_ACCRUAL_BALANCES_DATA_FAIL = 'GET_GENERIC_ACCRUAL_BALANCES_DATA_FAIL';
export const SET_REQUEST_ACCRUAL_BALANCES_DATA = 'SET_REQUEST_ACCRUAL_BALANCES_DATA';
export const FETCH_ACCRUAL_BALANCES_START = 'FETCH_ACCRUAL_BALANCES_START';
export const FETCH_ACCRUAL_BALANCES_SUCCESS = 'FETCH_ACCRUAL_BALANCES_SUCCESS';
export const FETCH_ACCRUAL_BALANCES_FAIL = 'FETCH_ACCRUAL_BALANCES_FAIL';
export const SET_PAGER_DATA_ACCRUAL_BALANCES = 'SET_PAGER_DATA_ACCRUAL_BALANCES';
export const REFRESH_ACCRUAL_BALANCES_LOADING  = 'REFRESH_ACCRUAL_BALANCES_LOADING';
export const CHANGE_PAGE_NUMBER_ACCRUAL_BALANCES = 'CHANGE_PAGE_NUMBER_ACCRUAL_BALANCES';
export const SORT_ACCRUAL_BALANCES = 'SORT_ACCRUAL_BALANCES';
export const SET_GENERIC_DATA_ACCRUAL_BALANCES_SUCCESS = 'SET_GENERIC_DATA_ACCRUAL_BALANCES_SUCCESS';
export const SET_GENERIC_DATA_ACCRUAL_BALANCES_FAIL = 'SET_GENERIC_DATA_ACCRUAL_BALANCES_FAIL';
// Accrual Balances Sagas
export const GET_GENERIC_DATA_ACCRUAL_BALANCES = 'GET_GENERIC_DATA_ACCRUAL_BALANCES';
export const FETCH_ACCRUAL_BALANCES = 'FETCH_ACCRUAL_BALANCES';
export const SET_GENERIC_DATA_ACCRUAL_BALANCES = 'SET_GENERIC_DATA_ACCRUAL_BALANCES';

// Recurring Schedules
export const FETCH_RECURRING_SCHEDULES_START = 'FETCH_RECURRING_SCHEDULES_START';
export const FETCH_RECURRING_SCHEDULES_SUCCESS = 'FETCH_RECURRING_SCHEDULES_SUCCESS';
export const FETCH_RECURRING_SCHEDULES_FAIL = 'FETCH_RECURRING_SCHEDULES_FAIL';
export const GET_GENERIC_DATA_RECURRING_SCHEDULES_START = 'GET_GENERIC_DATA_RECURRING_SCHEDULES_START';
export const GET_GENERIC_DATA_RECURRING_SCHEDULES_SUCCESS = 'GET_GENERIC_DATA_RECURRING_SCHEDULES_SUCCESS';
export const GET_GENERIC_DATA_RECURRING_SCHEDULES_FAIL = 'GET_GENERIC_DATA_RECURRING_SCHEDULES_FAIL';
export const SET_GENERIC_DATA_RECURRING_SCHEDULES_SUCCESS = 'SET_GENERIC_DATA_RECURRING_SCHEDULES_SUCCESS';
export const SET_GENERIC_DATA_RECURRING_SCHEDULES_FAIL = 'SET_GENERIC_DATA_RECURRING_SCHEDULES_FAIL';
export const SET_REQUEST_RECURRING_SCHEDULES_DATA = 'SET_REQUEST_RECURRING_SCHEDULES_DATA';
export const EXPORT_RECURRING_SCHEDULES_SUCCESS = 'EXPORT_RECURRING_SCHEDULES_SUCCESS';
export const CHANGE_PAGE_NUMBER_RECURRING_SCHEDULES = 'CHANGE_PAGE_NUMBER_RECURRING_SCHEDULES';
export const SET_PAGER_DATA_RECURRING_SCHEDULES = 'SET_PAGER_DATA_RECURRING_SCHEDULES';
export const REFRESH_LOADING_RECURRING_SCHEDULES  = 'REFRESH_LOADING_RECURRING_SCHEDULES';
export const SORT_RECURRING_SCHEDULES = 'SORT_RECURRING_SCHEDULES';
// Recurring Schedules Sagas
export const GET_GENERIC_RECURRING_SCHEDULES = 'GET_GENERIC_RECURRING_SCHEDULES';
export const FETCH_RECURRING_SCHEDULES = 'FETCH_RECURRING_SCHEDULES';
export const SET_GENERIC_DATA_RECURRING_SCHEDULES = 'SET_GENERIC_DATA_RECURRING_SCHEDULES';


// Recurring Templates
export const FETCH_RECURRING_TEMPLATES_START = 'FETCH_RECURRING_TEMPLATES_START';
export const FETCH_RECURRING_TEMPLATES_SUCCESS = 'FETCH_RECURRING_TEMPLATES_SUCCESS';
export const FETCH_RECURRING_TEMPLATES_FAIL = 'FETCH_RECURRING_TEMPLATES_FAIL';
export const GET_GENERIC_DATA_RECURRING_TEMPLATES_START = 'GET_GENERIC_DATA_RECURRING_TEMPLATES_START';
export const GET_GENERIC_DATA_RECURRING_TEMPLATES_SUCCESS = 'GET_GENERIC_DATA_RECURRING_TEMPLATES_SUCCESS';
export const GET_GENERIC_DATA_RECURRING_TEMPLATES_FAIL = 'GET_GENERIC_DATA_RECURRING_TEMPLATES_FAIL';
export const SET_GENERIC_DATA_RECURRING_TEMPLATES_SUCCESS = 'SET_GENERIC_DATA_RECURRING_TEMPLATES_SUCCESS';
export const SET_GENERIC_DATA_RECURRING_TEMPLATES_FAIL = 'SET_GENERIC_DATA_RECURRING_TEMPLATES_FAIL';
export const SET_REQUEST_RECURRING_TEMPLATES_DATA = 'SET_REQUEST_RECURRING_TEMPLATES_DATA';
export const EXPORT_RECURRING_TEMPLATES_SUCCESS = 'EXPORT_RECURRING_TEMPLATES_SUCCESS';
export const CHANGE_PAGE_NUMBER_RECURRING_TEMPLATES = 'CHANGE_PAGE_NUMBER_RECURRING_TEMPLATES';
export const SET_PAGER_DATA_RECURRING_TEMPLATES = 'SET_PAGER_DATA_RECURRING_TEMPLATES';
export const REFRESH_LOADING_RECURRING_TEMPLATES  = 'REFRESH_LOADING_RECURRING_TEMPLATES';
export const SORT_RECURRING_TEMPLATES = 'SORT_RECURRING_TEMPLATES';
// Recurring Templates Sagas
export const GET_GENERIC_RECURRING_TEMPLATES = 'GET_GENERIC_RECURRING_TEMPLATES';
export const FETCH_RECURRING_TEMPLATES = 'FETCH_RECURRING_TEMPLATES';
export const SET_GENERIC_DATA_RECURRING_TEMPLATES = 'SET_GENERIC_DATA_RECURRING_TEMPLATES';


// Time Sheet
export const FETCH_TIMESHEET_DATA_START = 'FETCH_TIMESHEET_DATA_START';
export const FETCH_TIMESHEET_DATA_SUCCESS = 'FETCH_TIMESHEET_DATA_SUCCESS';
export const FETCH_TIMESHEET_DATA_FAIL = 'FETCH_TIMESHEET_DATA_FAIL';
export const CHANGE_DATE_TIMESHEET = 'CHANGE_DATE_TIMESHEET';
export const SET_USER_ID = 'SET_USER_ID';
export const REFRESH_LOADING_TIMESHEET = 'REFRESH_LOADING_TIMESHEET';
export const FETCH_BRANCHES_TIMESHEET_START = 'FETCH_BRANCHES_START';
export const FETCH_BRANCHES_TIMESHEET_SUCCESS = 'FETCH_BRANCHES_TIMESHEET_SUCCESS';
export const FETCH_BRANCHES_TIMESHEET_ERROR= 'FETCH_BRANCHES_TIMESHEET_ERROR';
export const FETCH_DEPARTMENTS_TIMESHEET_START = 'FETCH_DEPARTMENTS_TIMESHEET_START';
export const FETCH_DEPARTMENTS_TIMESHEET_SUCCESS = 'FETCH_DEPARTMENTS_TIMESHEET_SUCCESS';
export const FETCH_DEPARTMENTS_TIMESHEET_ERROR= 'FETCH_DEPARTMENTS_TIMESHEET_ERROR';
// Time Sheet Sagas
export const FETCH_TIMESHEET_DATA = 'FETCH_TIMESHEET_DATA';
export const GET_PDF_TIMESHEET = 'GET_PDF_TIMESHEET';
export const FETCH_BRANCHES_TIMESHEET = 'FETCH_BRANCHES_TIMESHEET';
export const FETCH_DEPARTMENTS_TIMESHEET= 'FETCH_DEPARTMENTS_TIMESHEET';

// Extensions 
export const FETCH_EXCEPTIONS_DATA_START = 'FETCH_EXCEPTIONS_DATA_START';
export const FETCH_EXCEPTIONS_DATA_SUCCESS = 'FETCH_EXCEPTIONS_DATA_SUCCESS';
export const FETCH_EXCEPTIONS_DATA_FAIL= 'FETCH_EXCEPTIONS_DATA_FAIL';
export const GET_GENERIC_DATA_EXCEPTIONS_START = 'GET_GENERIC_DATA_EXCEPTIONS_START';
export const GET_GENERIC_DATA_EXCEPTIONS_SUCCESS = 'GET_GENERIC_DATA_EXCEPTIONS_SUCCESS';
export const GET_GENERIC_DATA_EXCEPTIONS_FAIL = 'GET_GENERIC_DATA_EXCEPTIONS_FAIL';
export const SET_GENERIC_DATA_EXCEPTIONS_SUCCESS = 'SET_GENERIC_DATA_EXCEPTIONS_SUCCESS';
export const SET_GENERIC_DATA_EXCEPTIONS_FAIL = 'SET_GENERIC_DATA_EXCEPTIONS_FAIL';
export const SET_REQUEST_EXCEPTIONS_DATA = 'SET_REQUEST_EXCEPTIONS_DATA';
export const EXPORT_EXCEPTIONS_SUCCESS = 'EXPORT_EXCEPTIONS_SUCCESS';
export const CHANGE_PAGE_NUMBER_EXCEPTIONS = 'CHANGE_PAGE_NUMBER_EXCEPTIONS';
export const SET_PAGER_DATA_EXCEPTIONS = 'SET_PAGER_DATA_EXCEPTIONS';
export const REFRESH_LOADING_EXCEPTIONS = 'REFRESH_LOADING_EXCEPTIONS';
export const SORT_EXCEPTIONS = 'SORT_EXCEPTIONS';
export const GET_PDF_TIMESHEET_SUCCESS = 'GET_PDF_TIMESHEET_SUCCESS';
// Extensions Sagas
export const FETCH_EXCEPTIONS_DATA = 'FETCH_EXCEPTIONS_DATA';
export const GET_GENERIC_EXCEPTIONS= 'GET_GENERIC_EXCEPTIONS';
export const SET_GENERIC_DATA_EXCEPTIONS = 'SET_GENERIC_DATA_EXCEPTIONS';

// Requests 
export const FETCH_REQUESTS_DATA_START = 'FETCH_REQUESTS_DATA_START';
export const FETCH_REQUESTS_DATA_SUCCESS = 'FETCH_REQUESTS_DATA_SUCCESS';
export const FETCH_REQUESTS_DATA_FAIL= 'FETCH_REQUESTS_DATA_FAIL';
export const GET_GENERIC_DATA_REQUESTS_START = 'GET_GENERIC_DATA_REQUESTS_START';
export const GET_GENERIC_DATA_REQUESTS_SUCCESS = 'GET_GENERIC_DATA_REQUESTS_SUCCESS';
export const GET_GENERIC_DATA_REQUESTS_FAIL = 'GET_GENERIC_DATA_REQUESTS_FAIL';
export const SET_GENERIC_DATA_REQUESTS_SUCCESS = 'SET_GENERIC_DATA_REQUESTS_SUCCESS';
export const SET_GENERIC_DATA_REQUESTS_FAIL = 'SET_GENERIC_DATA_REQUESTS_FAIL';
export const SET_REQUEST_REQUESTS_DATA = 'SET_REQUEST_REQUESTS_DATA';
export const EXPORT_REQUESTS_SUCCESS = 'EXPORT_REQUESTS_SUCCESS';
export const CHANGE_PAGE_NUMBER_REQUESTS = 'CHANGE_PAGE_NUMBER_REQUESTS';
export const SET_PAGER_DATA_REQUESTS = 'SET_PAGER_DATA_REQUESTS';
export const REFRESH_LOADING_REQUESTS = 'REFRESH_LOADING_REQUESTS';
export const SORT_REQUESTS = 'SORT_REQUESTS';
export const GET_REQUEST_TYPES_START = 'GET_REQUEST_TYPES_START';
export const GET_REQUEST_TYPES_SUCCESS= 'GET_REQUEST_TYPES_SUCCESS';
export const GET_REQUEST_TYPES_FAIL = 'GET_REQUEST_TYPES_FAIL';
export const GET_REQUEST_DIRECT_MANAGER_START = 'GET_REQUEST_DIRECT_MANAGER_START';
export const GET_REQUEST_DIRECT_MANAGER_SUCCESS= 'GET_REQUEST_DIRECT_MANAGER_SUCCESS';
export const GET_REQUEST_DIRECT_MANAGER_FAIL = 'GET_REQUEST_DIRECT_MANAGER_FAIL';
export const GET_REQUEST_SHIFTS_START = 'GET_REQUEST_SHIFTS_START';
export const GET_REQUEST_SHIFTS_SUCCESS = 'GET_REQUEST_SHIFTS_SUCCESS';
export const GET_REQUEST_SHIFTS_FAIL = 'GET_REQUEST_SHIFTS_FAIL';
export const GET_REPORT_TO_USER_REQUESTS_START = 'GET_REPORT_TO_USER_REQUESTS_START'
export const GET_REPORT_TO_USER_REQUESTS_SUCCESS = 'GET_REPORT_TO_USER_REQUESTS_SUCCESS'
export const GET_REPORT_TO_USER_REQUESTS_FAIL = 'GET_REPORT_TO_USER_REQUESTS_FAIL'
export const VALIDATE_REQUEST_START = 'VALIDATE_REQUEST_START'
export const VALIDATE_REQUEST_SUCCESS = 'VALIDATE_REQUEST_SUCCESS'
export const VALIDATE_REQUEST_FAIL = 'VALIDATE_REQUEST_FAIL'
export const RESET_VALIDATE_REQUEST = 'RESET_VALIDATE_REQUEST'
export const SET_NEW_REQUEST_START = 'SET_NEW_REQUEST_START'
export const SET_NEW_REQUEST_SUCCESS = 'SET_NEW_REQUEST_SUCCESS'
export const SET_NEW_REQUEST_FAIL = 'SET_NEW_REQUEST_FAIL'
export const SET_NEW_REQUEST_REQUEST_DATA = 'SET_NEW_REQUEST_REQUEST_DATA'
export const CANCEL_REQUESTS_START = 'CANCEL_REQUESTS_START'
export const CANCEL_REQUESTS_SUCCESS = 'CANCEL_REQUESTS_SUCCESS'
export const CANCEL_REQUESTS_FAIL = 'CANCEL_REQUESTS_FAIL';
export const RESET_CANCEL_REQUEST = 'RESET_CANCEL_REQUEST'
export const CHANGE_FILTER_DATA_REQUESTS = 'CHANGE_FILTER_DATA_REQUESTS'
export const CLEAR_FILTER_DATA = 'CLEAR_FILTER_DATA';
export const GET_REQUEST_STATUSES_START = 'GET_REQUEST_STATUSES_START';
export const GET_REQUEST_STATUSES_SUCCESS = 'GET_REQUEST_STATUSES_SUCCESS';
export const GET_REQUEST_STATUSES_FAIL = 'GET_REQUEST_STATUSES_FAIL';
export const GET_REQUEST_START = 'GET_REQUEST_START'
export const GET_REQUEST_SUCCESS = 'GET_REQUEST_SUCCESS'
export const GET_REQUEST_FAIL = 'GET_REQUEST_FAIL';
export const GET_REQUEST_AUTH_HISTORY_START = 'GET_REQUEST_AUTH_HISTORY_START';
export const GET_REQUEST_AUTH_HISTORY_SUCCESS = 'GET_REQUEST_AUTH_HISTORY_SUCCESS';
export const GET_REQUEST_AUTH_HISTORY_FAIL = 'GET_REQUEST_AUTH_HISTORY_FAIL';
export const GET_ABSENCE_POLICIES_START = 'GET_ABSENCE_POLICIES_START'
export const GET_ABSENCE_POLICIES_SUCCESS = 'GET_ABSENCE_POLICIES_SUCCESS'
export const GET_ABSENCE_POLICIES_FAIL= 'GET_ABSENCE_POLICIES_FAIL'
export const GET_USER_SHIFTS_FOR_VACATION_START = 'GET_USER_SHIFTS_FOR_VACATION_START'
export const GET_USER_SHIFTS_FOR_VACATION_SUCCESS = 'GET_USER_SHIFTS_FOR_VACATION_SUCCESS'
export const GET_USER_SHIFTS_FOR_VACATION_FAIL = 'GET_USER_SHIFTS_FOR_VACATION_FAIL'
export const GET_HOURLY_ABSENCE_POLICIES_START = 'GET_HOURLY_ABSENCE_POLICIES_START'
export const GET_HOURLY_ABSENCE_POLICIES_SUCCESS = 'GET_HOURLY_ABSENCE_POLICIES_SUCCESS'
export const GET_HOURLY_ABSENCE_POLICIES_FAIL= 'GET_HOURLY_ABSENCE_POLICIES_FAIL'
export const GET_USER_SCHEDULES_BY_REQUEST_TYPE_START = 'GET_USER_SCHEDULES_BY_REQUEST_TYPE_START'
export const GET_USER_SCHEDULES_BY_REQUEST_TYPE_SUCCESS = 'GET_USER_SCHEDULES_BY_REQUEST_TYPE_SUCCESS'
export const GET_USER_SCHEDULES_BY_REQUEST_TYPE_FAIL = 'GET_USER_SCHEDULES_BY_REQUEST_TYPE_FAIL'
export const GET_ANOTHER_USERS_REQUEST_START = 'GET_ANOTHER_USERS_REQUEST_START'
export const GET_ANOTHER_USERS_REQUEST_SUCCESS = 'GET_ANOTHER_USERS_REQUEST_SUCCESS'
export const GET_ANOTHER_USERS_REQUEST_FAIL = 'GET_ANOTHER_USERS_REQUEST_FAIL'


// Requests Sagas
export const FETCH_REQUESTS_DATA = 'FETCH_REQUESTS_DATA';
export const GET_GENERIC_REQUESTS = 'GET_GENERIC_REQUESTS';
export const SET_GENERIC_DATA_REQUESTS = 'SET_GENERIC_DATA_REQUESTS';
export const GET_REQUEST_TYPES = 'GET_REQUEST_TYPES'
export const GET_REQUEST_DIRECT_MANAGER = 'GET_REQUEST_DIRECT_MANAGER';
export const GET_REQUEST_SHIFTS = 'GET_REQUEST_SHIFTS';
export const GET_REPORT_TO_USER_REQUESTS = 'GET_REPORT_TO_USER_REQUESTS'
export const VALIDATE_REQUEST = 'VALIDATE_REQUEST'
export const SET_NEW_REQUEST = 'SET_NEW_REQUEST'
export const CANCEL_REQUESTS = 'CANCEL_REQUESTS'
export const GET_REQUEST_STATUSES = 'GET_REQUEST_STATUSES';
export const GET_REQUEST = 'GET_REQUEST'
export const GET_REQUEST_AUTH_HISTORY = 'GET_REQUEST_AUTH_HISTORY';
export const GET_ABSENCE_POLICIES = 'GET_ABSENCE_POLICIES'
export const GET_USER_SHIFTS_FOR_VACATION = 'GET_USER_SHIFTS_FOR_VACATION'
export const GET_HOURLY_ABSENCE_POLICIES = 'GET_HOURLY_ABSENCE_POLICIES'
export const GET_USER_SCHEDULES_BY_REQUEST_TYPE = 'GET_USER_SCHEDULES_BY_REQUEST_TYPE'
export const GET_ANOTHER_USERS_REQUEST = 'GET_ANOTHER_USERS_REQUEST'
export const CHANGE_NEW_REQUEST_STATUS = 'CHANGE_NEW_REQUEST_STATUS'


// Request auth
export const GET_GENERIC_DATA_AUTH_REQUEST_START = 'GET_GENERIC_DATA_AUTH_REQUEST_START';
export const GET_GENERIC_DATA_AUTH_REQUEST_SUCCESS = 'GET_GENERIC_DATA_AUTH_REQUEST_SUCCESS';
export const GET_GENERIC_DATA_AUTH_REQUEST_FAIL = 'GET_GENERIC_DATA_AUTH_REQUEST_FAIL';
export const SET_GENERIC_DATA_AUTH_REQUEST_FAIL = 'SET_GENERIC_DATA_AUTH_REQUEST_FAIL';
export const SET_GENERIC_DATA_AUTH_REQUEST = 'SET_GENERIC_DATA_AUTH_REQUEST'
export const FETCH_REQUEST_AUTH_DATA_START = 'FETCH_REQUEST_AUTH_DATA_START'
export const FETCH_REQUEST_AUTH_DATA_SUCCESS = 'FETCH_REQUEST_AUTH_DATA_SUCCESS'
export const FETCH_REQUESTS_AUTH_DATA_FAIL = 'FETCH_REQUESTS_AUTH_DATA_FAIL'
export const SET_AUTH_REQUEST_DATA = 'SET_AUTH_REQUEST_DATA'
export const SET_PAGER_DATA_AUTH_REQUEST = 'SET_PAGER_DATA_AUTH_REQUEST'
export const CHANGE_PAGE_NUMBER_AUTH_REQUEST = 'CHANGE_PAGE_NUMBER_AUTH_REQUEST'
export const REFRESH_LOADING_AUTH_REQUEST = 'REFRESH_LOADING_AUTH_REQUEST'
export const SORT_AUTH_REQUEST = 'SORT_AUTH_REQUEST'
export const CHANGE_FILTER_DATA_AUTH_REQUEST = 'CHANGE_FILTER_DATA_AUTH_REQUEST'
export const CLEAR_FILTER_DATA_AUTH_REQUEST = 'CLEAR_FILTER_DATA_AUTH_REQUEST'
export const GET_AUTH_REQUEST_TYPES_START = 'GET_AUTH_REQUEST_TYPES_START'
export const GET_AUTH_REQUEST_TYPES_SUCCESS = 'GET_AUTH_REQUEST_TYPES_SUCCESS'
export const GET_AUTH_REQUEST_TYPES_FAIL = 'GET_AUTH_REQUEST_TYPES_FAIL'
export const GET_AUTH_REQUEST_START = 'GET_AUTH_REQUEST_START'
export const GET_AUTH_REQUEST_SUCCESS = 'GET_AUTH_REQUEST_SUCCESS'
export const GET_AUTH_REQUEST_FAIL = 'GET_AUTH_REQUEST_FAIL';
export const AUTHORIZE_REQUEST_START = 'AUTHORIZE_REQUEST_START'
export const AUTHORIZE_REQUEST_SUCCESS = 'AUTHORIZE_REQUEST_SUCCESS'
export const AUTHORIZE_REQUEST_FAIL = 'AUTHORIZE_REQUEST_FAIL'
export const CHANGE_USER_ID_PENDING_REQUESTS = 'CHANGE_USER_ID_PENDING_REQUESTS'
export const RESET_AUTORIZE = 'RESET_AUTORIZE'

//Request auth sagas
export const GET_GENERIC_DATA_AUTH_REQUEST = 'GET_GENERIC_DATA_AUTH_REQUEST'
export const FETCH_REQUEST_AUTH_DATA = 'FETCH_REQUEST_AUTH_DATA'
export const GET_REQUEST_AUTH_TYPES = 'GET_REQUEST_AUTH_TYPES'
export const GET_AUTH_REQUEST = 'GET_AUTH_REQUEST'
export const AUTHORIZE_REQUEST = 'AUTHORIZE_REQUEST'
export const SET_CURRENT_MONTH = 'SET_CURRENT_MONTH'
export const SET_CURRENT_YEAR = 'SET_CURRENT_YEAR';
export const SELECT_DATE_USER_PROFILE = 'SELECT_DATE_USER_PROFILE';
export const RESET_CALENDAR_DATA = 'RESET_CALENDAR_DATA'

// User
export const GET_USER_DATA_START = 'GET_USER_DATA_START'
export const GET_USER_DATA_SUCCESS = 'GET_USER_DATA_SUCCESS'
export const GET_USER_DATA_FAIL = 'GET_USER_DATA_FAIL'
export const GET_TIMESHEET_FOR_MONTH_START = 'GET_TIMESHEET_FOR_MONTH_START'
export const GET_TIMESHEET_FOR_MONTH_SUCCESS = 'GET_TIMESHEET_FOR_MONTH_SUCCESS'
export const GET_TIMESHEET_FOR_MONTH_FAIL = 'GET_TIMESHEET_FOR_MONTH_FAIL'
export const GET_AVAILABLE_BALANCE_START = 'GET_AVAILABLE_BALANCE_START'
export const GET_AVAILABLE_BALANCE_SUCCESS = 'GET_AVAILABLE_BALANCE_SUCCESS'
export const GET_AVAILABLE_BALANCE_FAIL = 'GET_AVAILABLE_BALANCE_FAIL'
export const GET_PROCESSED_DATA_START = 'GET_PROCESSED_DATA_START'
export const GET_PROCESSED_DATA_SUCCESS = 'GET_PROCESSED_DATA_SUCCESS'
export const GET_PROCESSED_DATA_FAIL = 'GET_PROCESSED_DATA_FAIL'
export const GET_USER_SUBORDINATES_START = 'GET_USER_SUBORDINATES_START'
export const GET_USER_SUBORDINATES_SUCCESS = 'GET_USER_SUBORDINATES_SUCCESS'
export const GET_USER_SUBORDINATES_FAIL = 'GET_USER_SUBORDINATES_FAIL'
export const SET_PAGER_DATA_SUBORDINATES = 'SET_PAGER_DATA_SUBORDINATES'
export const SET_USER_ID_ATTENDANDANCE = 'SET_USER_ID_ATTENDANDANCE'
// export const CHANGE_PAGE_NUMBER_SUBORDINATES = 'CHANGE_PAGE_NUMBER_SUBORDINATES'

// Users sagas
export const GET_USER_DATA = 'GET_USER_DATA'
export const GET_TIMESHEET_FOR_MONTH = 'GET_TIMESHEET_FOR_MONTH'
export const GET_AVAILABLE_BALANCE = 'GET_AVAILABLE_BALANCE'
export const GET_PROCESSED_DATA = 'GET_PROCESSED_DATA'
export const GET_USER_SUBORDINATES = 'GET_USER_SUBORDINATES'


// Team
export const GET_TEAM_INFO_START = 'GET_TEAM_INFO_START'
export const GET_TEAM_INFO_SUCCESS = 'GET_TEAM_INFO_SUCCESS'
export const GET_TEAM_INFO_FAIL = 'GET_TEAM_INFO_FAIL'
export const GET_TEAM_MEMBERS_START = 'GET_TEAM_MEMBERS_START'
export const GET_TEAM_MEMBERS_SUCCESS = 'GET_TEAM_MEMBERS_SUCCESS'
export const GET_TEAM_MEMBERS_FAIL = 'GET_TEAM_MEMBERS_FAIL'
export const GET_TOTAL_ATTENDANCE_START = 'GET_TOTAL_ATTENDANCE_START'
export const GET_TOTAL_ATTENDANCE_SUCCESS = 'GET_TOTAL_ATTENDANCE_SUCCESS'
export const GET_TOTAL_ATTENDANCE_FAIL = 'GET_TOTAL_ATTENDANCE_FAIL'
export const EMPLOYEES_ON_VACATION_START = 'EMPLOYEES_ON_VACATION_START'
export const EMPLOYEES_ON_VACATION_SUCCESS= 'EMPLOYEES_ON_VACATION_SUCCESS'
export const EMPLOYEES_ON_VACATION_FAIL = 'EMPLOYEES_ON_VACATION_FAIL'
export const EXCUSED_LEAVES_TODAY_START= 'EXCUSED_LEAVES_TODAY_START'
export const EXCUSED_LEAVES_TODAY_SUCCESS = 'EXCUSED_LEAVES_TODAY_SUCCESS'
export const EXCUSED_LEAVES_TODAY_FAIL = 'EXCUSED_LEAVES_TODAY_FAIL'
export const EMPLOYEES_ON_VACATION_LIST_START = 'EMPLOYEES_ON_VACATION_LIST_START'
export const EMPLOYEES_ON_VACATION_LIST_SUCCESS = 'EMPLOYEES_ON_VACATION_LIST_SUCCESS'
export const EMPLOYEES_ON_VACATION_LIST_FAIL = 'EMPLOYEES_ON_VACATION_LIST_FAIL'
export const EXUSED_LEAVES_LIST_START = 'EXUSED_LEAVES_LIST_START'
export const EXUSED_LEAVES_LIST_SUCCESS = 'EXUSED_LEAVES_LIST_SUCCESS'
export const EXUSED_LEAVES_LIST_FAIL = 'EXUSED_LEAVES_LIST_FAIL'
export const ABSENT_EMPLOYEES_LIST_START = 'ABSENT_EMPLOYEES_LIST_START'
export const ABSENT_EMPLOYEES_LIST_SUCCESS = 'ABSENT_EMPLOYEES_LIST_SUCCESS'
export const ABSENT_EMPLOYEES_LIST_FAIL = 'ABSENT_EMPLOYEES_LIST_FAIL'

// Team sagas
export const GET_TEAM_INFO = 'GET_TEAM_INFO'
export const GET_TEAM_MEMBERS = 'GET_TEAM_MEMBERS'
export const GET_TOTAL_ATTENDANCE = 'GET_TOTAL_ATTENDANCE'
export const EMPLOYEES_ON_VACATION = 'EMPLOYEES_ON_VACATION'
export const EXCUSED_LEAVES_TODAY = 'EXCUSED_LEAVES_TODAY'
export const EMPLOYEES_ON_VACATION_LIST = 'EMPLOYEES_ON_VACATION_LIST'
export const EXUSED_LEAVES_LIST = 'EXUSED_LEAVES_LIST'
export const ABSENT_EMPLOYEES_LIST = 'ABSENT_EMPLOYEES_LIST'

// Me 
export const GET_ME_DATA = 'GET_ME_DATA'
export const EDIT_USER_START = 'EDIT_USER_START'
export const EDIT_USER_SUCCESS = 'EDIT_USER_SUCCESS'
export const EDIT_USER_FAIL = 'EDIT_USER_FAIL'
export const EDIT_USER_RESET = 'EDIT_USER_RESET'
export const SET_AVATAR = 'SET_AVATAR'

// Me sagas
export const GET_ME_DATA_START = 'GET_ME_DATA_START'
export const GET_ME_DATA_SUCCESS = 'GET_ME_DATA_SUCCESS'
export const GET_ME_DATA_FAIL = 'GET_ME_DATA_FAIL'
export const CHANGE_AVATAR = 'CHANGE_AVATAR'
export const EDIT_USER = 'EDIT_USER'

// Punch In/Out
export const GET_USER_PUNCH_START = 'GET_USER_PUNCH_START'
export const GET_USER_PUNCH_SUCCESS = 'GET_USER_PUNCH_SUCCESS'
export const GET_USER_PUNCH_FAIL = 'GET_USER_PUNCH_FAIL'
export const GET_PUNCH_STATUSES_START = 'GET_PUNCH_STATUSES_START'
export const GET_PUNCH_STATUSES_SUCCESS = 'GET_PUNCH_STATUSES_SUCCESS'
export const GET_PUNCH_STATUSES_FAIL = 'GET_PUNCH_STATUSES_FAIL'
export const GET_PUNCH_TYPES_START = 'GET_PUNCH_TYPES_START'
export const GET_PUNCH_TYPES_SUCCESS = 'GET_PUNCH_TYPES_SUCCESS'
export const GET_PUNCH_TYPES_FAIL = 'GET_PUNCH_TYPES_FAIL'
export const SET_USER_PUNCH_START = 'SET_USER_PUNCH_START'
export const SET_USER_PUNCH_SUCCESS = 'SET_USER_PUNCH_SUCCESS'
export const SET_USER_PUNCH_FAIL = 'SET_USER_PUNCH_FAIL'
export const SET_PUNCH_STATUS_ID = 'SET_PUNCH_STATUS_ID'
export const SET_PUNCH_TYPE_ID = 'SET_PUNCH_TYPE_ID'
export const CHANGE_PUNCH_STATUS = 'CHANGE_PUNCH_STATUS'

// Punch In/Out sagas
export const GET_USER_PUNCH = 'GET_USER_PUNCH'
export const GET_PUNCH_STATUSES = 'GET_PUNCH_STATUSES'
export const GET_PUNCH_TYPES = 'GET_PUNCH_TYPES'
export const SET_USER_PUNCH = 'SET_USER_PUNCH'


// Home
export const FETCH_USERS_WITH_BIRTHDAY_START = 'FETCH_USERS_WITH_BIRTHDAY_START'
export const FETCH_USERS_WITH_BIRTHDAY_SUCCESS = 'FETCH_USERS_WITH_BIRTHDAY_SUCCESS'
export const FETCH_USERS_WITH_BIRTHDAY_FAIL = 'FETCH_USERS_WITH_BIRTHDAY_FAIL'
export const FETCH_NEW_MEMBERS_START = 'FETCH_NEW_MEMBERS_START'
export const FETCH_NEW_MEMBERS_SUCCESS = 'FETCH_NEW_MEMBERS_SUCCESS'
export const FETCH_NEW_MEMBERS_FAIL = 'FETCH_NEW_MEMBERS_FAIL'


// Home sagas
export const FETCH_USERS_WITH_BIRTHDAY = 'FETCH_USERS_WITH_BIRTHDAY'
export const FETCH_NEW_MEMBERS = 'FETCH_NEW_MEMBERS'

// Company 
export const FETCH_DIVISIONS_START = 'FETCH_DIVISIONS_START'
export const FETCH_DIVISIONS_SUCCESS = 'FETCH_DIVISIONS_SUCCESS'
export const FETCH_DIVISIONS_FAIL = 'FETCH_DIVISIONS_FAIL';
export const FETCH_DEPARTMENTS_START = 'FETCH_DEPARTMENTS_START'
export const FETCH_DEPARTMENTS_SUCCESS = 'FETCH_DEPARTMENTS_SUCCESS'
export const FETCH_DEPARTMENTS_FAIL = 'FETCH_DEPARTMENTS_FAIL'

// Company sagas
export const FETCH_DIVISIONS = 'FETCH_DIVISIONS'
export const FETCH_DEPARTMENTS = 'FETCH_DEPARTMENTS'

// Common
export const TOGGLE_SIDEBAR = 'TOGGLE_SIDEBAR';

export const TEST_TYPE = 'TEST_TYPE'