const ar = {
    global: {
        default_view: 'الواجهة الافتراضية',
        loading: 'جار التحميل',
        print: 'طباعة',
        export: 'تصدير',
        actual_punches: 'البصمات الفعلية',
        schedules: 'الشفتات',
        attendance: 'الحضور',
        employees: 'الموظفين',
        report: 'تقرير',
        my_account: 'حسابي',
        help: 'مساعدة',
        schedule: 'جدول',
        authorization: 'ترخيص',
        logout: 'الخروج',
        new: "الجديد",
        view: 'رأي',
        send: "إرسال",
        cancel: 'إلغاء',
        cancel_request: 'إلغاء الطلب',
        authtorize: 'يأذن',
        decline: 'انخفاض',
        home: 'الصفحة الرئيسية',
        team: 'الفريق',
        company: 'شركة',
        me: 'أنا',
        settings: 'الإعدادات',
        policies: 'السياسات',
        departments: 'الإدارات',
        about: 'Earthlink حول',
        back: 'عودة',
        punch_in_out: 'لكمة في / خارج',
        new_request: 'طلب جديد',
        pending_requests: 'الطلبات المعلقة',
        notifications: 'إشعارات',
        user_requests: 'الطلبات المعلقة من قبل المستخدم',
        make_request_as_user: 'تقديم طلب كمستخدم',
        email: 'البريد الإلكتروني',
        work_phone: 'هاتف عمل',
        available_today: 'المتاحة اليوم',
        mobile_number: 'رقم الهاتف المحمول',
        not_provided: 'غير مزود',
        user_id: 'معرف المستخدم',
        hire_date: 'موعد التوظيف',
        section: 'الجزء',
        department: 'قسم',
        length_of_service: 'مدة الخدمة',
        available_balance: 'الرصيد المتوفر',
        available_balance_types: '(كل ساعة ، سنوية ، أوراق مرنة)',
        extra_information: 'معلومات اضافية',
        reset: 'إعادة تعيين',
        today: 'اليوم',
        selected_date: 'التاريخ المحدد',
        errors_codes: 'أخطاء رموز',
        in: 'في',
        out: 'خارج',
        vacation: 'اجازة',
        leaves: 'اوراق اشجار',
        absence: 'غياب',
        exceptions: 'الاستثناءات',
        attendance_kpis: 'الحضور KPIS',
        working_hours: 'ساعات العمل',
        excuse_leaves: 'أوراق العذر',
        absence_days: 'أيام الغياب',
        from: 'من',
        to: 'الى',
        vacations: 'الاجازات',
        subordinates: 'المرؤوسين',
        employee: 'الموظف',
        full_name: "الاسم الكامل",
        job_title: 'المسمى الوظيفي',
        displaying: 'عرض',
        total: 'مجموع',
        view_profile: 'عرض ملف التعريف',
        no_results: 'آسف ، لا توجد نتائج ل',
        try_different_keywords: 'جرب كلمات رئيسية مختلفة',
        find_request: 'البحث عن طلب',
        selected_from: "مختارة من", 
        select_first_date: 'يرجى اختيار اليوم الأول',
        select_last_date: 'يرجى اختيار اليوم الأخير',
        show_processed_data: 'إظهار البيانات المعالجة لـ',
        users_in_total: 'المستخدمين في المجموع',
        success: 'نجاح',
        process_failed: 'فشلت العملية',
        show_more: 'أظهر المزيد',
        my_pending_requests: 'طلباتي المعلقة',
        edit: 'تصحيح',
        requests: 'طلبات',
        basic_info: 'تحرير المعلومات الأساسية',
        save: 'حفظ',
        account_info: 'معلومات الحساب',
        start_date: 'تاريخ',
        full_arabic_name: 'الاسم العربي الكامل',
        hour: 'ساعة',
        hours: 'ساعات',
        days: 'الأيام',
        day: 'اليوم',
        minute: 'دقيقة',
        minutes: 'دقائق',
        years: 'سنوات',
        previous: 'سابق',
        next: 'التالى',
        time: 'زمن',
        date: 'تاريخ',
        punch_type: 'نوع لكمة',
        in_out: 'في خارج',
        leave_type: 'نوع الإجازة',
        online: 'عبر الانترنت',
        offline: 'غير متصل على الانترنت',
        month_view: 'عرض الشهر',
        week_view: 'عرض الأسبوع',
        day_view: 'عرض اليوم',
        about_elteam: 'Earthlink حول',
        hierarchy: 'التسلسل الهرمي',
        elteam_journal: 'Earthlink مجلة',
        blog: 'مدونة',
        internal_vacancies: 'الشواغر الداخلية',
        company_hierarchy: 'شركة - التسلسل الهرمي',
    },
    dropdown: {
        employee_number: 'الموظف#',
        full_arabic_name: 'الاسم العربي الكامل',
        default_department: 'قسم',
        status: 'الحالة',
        full_name: 'الاسم الكامل',
        report_to_user: 'تقرير للمستخدم',
        work_phone: 'هاتف عمل',
        work_email: 'البريد الإلكتروني العمل',
        any: 'أي',
        name: 'اسم',
        type: 'نوع',
        date_stamp1: 'تاريخ',
        duration: 'المدة الزمنية',
        absence_policy: 'سياسة الغياب',
        shift: 'تحول',
        shift2: 'التحول الجديد'
    },
    actual_punches: {
        pageTitle: 'البصمات الفعلية',
    },
    recurring_templates: {
        pageTitle: 'النماذج الدورية',
    },
    recurring_schedules: {
        pageTitle: 'الشفتات الدورية',
    },
    accrual_balances: {
        pageTitle: 'الارصدة',
        first_name: 'الاسم الاول',
        last_name: 'اللقب',
        accrual_policy_account: 'حساب',
        balance: 'رصيد',
        default_department: 'قسم'
    },
    timesheet: {
        pageTitle: 'سجل الدوام',
        employee: 'الموظف',
        in: 'دخول',
        out: 'خروج',
        request: 'طلب',
        exceptions: 'الاستثناءات',
        total_time: 'الوقت الكلي',
        worked_time: 'الوقت عملت',
        regular_time: 'الوقت العادية',
        statutory_holiday: 'عطلة النظاميتين',
        hourly_leave_balance: 'رصيد الإجازة في الساعة',
        vacation_unpaid: 'إجازة غير مدفوعة الأجر',
        hourly_leave_balance_withdrawal: 'كل ساعة إجازة سحب الرصيد',
        accumulated_time: 'الوقت المتراكم',
        absence: 'غياب',
        week: 'اسبوع',
        pay_period: 'فترة السداد',
        vacation_paid: 'عطلة مدفوعة',
        employee_number: 'الموظف#',
        full_arabic_name: 'الاسم العربي الكامل',
        default_department: 'قسم',
        status: 'الحالة',
        full_name: 'الاسم الكامل',
        report_to_user: 'تقرير للمستخدم',
        vacation: 'عطلة',
        branch: 'فرع',
        no_branch: 'لا فرع',
        hq4: 'HQ4',
        department: 'قسم',
        software_research_and_development: 'بحث وتطوير البرمجيات',
        no_department: 'لا قسم',
        hourly_leave_paid: 'كل إجازة مدفوعة الأجر',
        work_phone: 'هاتف عمل',
        work_email: 'البريد الإلكتروني العمل',
        employees: 'الموظفين',
    },
    exceptions: {
        pageTitle: 'الاستثناءات',
        first_name: 'الاسم الاول',
        last_name: 'اللقب',
        date_stamp: 'التاريخ',
        severity: 'درجة الخطورة',
        exception_policy_type: 'الاستثناءات',
        exception_policy_type_id: 'الرمز',
        shift_type: 'نوع التحول',
        time_difference: 'فارق التوقيت',
        title: 'عنوان',
        group: 'مجموعة',
        default_branch: 'الفرع الافتراضي',
        default_department: 'القسم الافتراضي',
        branch: 'الفرع"',
        department: 'القسم',
        country: 'البلد',
        province: 'المقاطعة',
        policy_group: 'مجموعة السياسات',
        permission_group: 'مجموعة الأذونات',
        pay_period_schedule: 'جدول فترة الدفع',
        created_by: 'تم الإنشاء بواسطة',
        created_date: 'تاريخ الانشاء',
        updated_by: 'تم التحديث بواسطة',
        updated_date: 'تاريخ التحديث'
    },
    tabs: {
        basic_search: 'بحث',
        saved_search: 'بحث متقدم',
        advanced_search: 'البحث المتقدم'
    },
    schedules: {
        pageTitle: 'الشفتات'
    },
    punches: {
        pageTitle: 'البصمات'
    },
    accrual_schedule: {
        pageTitle: 'جدول الاستحقاق'
    },
    custom_schedules: {
        pageTitle: 'الشفتات الخاصة'
    },
    requests: {
        pageTitle: 'طلبات',
        employee_number: "الموظف",
        full_name: 'الاسم الكامل',
        type: 'النوع',
        status: 'الحالة',
        date_stamp1: 'تاريخ الوقت',
        date_stamp: 'تاريخ الوقت',
        duration: "المدة",
        absence_policy: "سياسة الغياب",
        shift: 'شفت',
        shift2: 'التحول الجديد',
        fill_in_user: 'مستخدم آخر',
        message: 'رسالة',
        current_authorization_user: 'مستخدم التفويض الحالي',
        approvals_display: 'الموافقات',
        created_date: 'تاريخ الانشاء',
        employee: 'الموظف',
        start_date: 'تاريخ البدء',
        end_date: 'تاريخ الانتهاء',
        created_by: 'تم الإنشاء بواسطة',
        updated_by: 'اخر تحديث بواسطة',
        other_user: 'مستخدم آخر',
        clear_search: 'مسح البحث',
        search: 'بحث',
        request_type: 'نوع الطلب',
        apply_for: 'التقدم بطلب للحصول',
        direct_manager: 'المدير المباشر',
        date_from: 'التاريخ من',
        reason_message: 'السبب / رسالة',
        date_to: 'تاريخ ل',
        new_request: 'طلب جديد',
        punch_status: 'لكمة الحالة',
        punch_date: 'لكمة التاريخ',
        punch_time: 'لكمة الوقت',
        date: 'التاريخ',
        start_time: 'وقت البدء',
        end_time: 'وقت النهاية',
        users: 'المستخدمين',
        schedule: 'جدول',
        another_employee: 'موظف آخر',
        off_day: 'يوم خارج',
        punch_in_time: 'لكمة في الوقت المناسب',
        punch_out_time: 'لكمة خارج الوقت',
        ticket_id: 'معرف التذكرة',
        approvals: 'الموافقات',
        job_location: 'مكان العمل',
        request: 'طلب',
        authorization_history: 'تاريخ الترخيص',
        authorized: 'مخول',
        employee_shift: 'تحول الموظف',
        cancel: 'إلغاء',
        send: "إرسال",
        request_sent: 'تم إرسال طلبك الجديد',
        request_failed: 'فشل الطلب الخاص بك بنجاح',
        approved: 'وافق',
        approved_message: 'تمت الموافقة على الطلب',
        declined: 'رفض',
        declined_message: 'تم رفض الطلب',
        failed: 'فشلت العملية',
        failed_message: 'فشل الطلب الخاص بك بنجاح'
    },
    messages: {
        pageTitle: 'الرسائل'
    },
    preferences: {
        pageTitle: 'الاعدادات'
    },
    request_authorizations: {
        pageTitle: 'ترخيص الطلبات'
    },
    logout: {
        pageTitle: 'تسجيل الخروج'
    },
    errors: {
        no_results_found: 'لا توجد نتائج',
        request_not_canceled: 'طلب غير ملغى',
        server_error: 'خطأ في الخادم',
        no_birthday: 'لا أعياد ميلاد جديدة',
        no_new_members: 'لا يوجد أعضاء جدد',
        not_permissions: 'ليس أذونات'
    },
    authRequests: {
        employee_number: 'الموظف#',
        full_name: 'الاسم الكامل',
        type: 'نوع',
        status: 'الحالة',
        date_stamp1: 'تاريخ الوقت',
        duration: 'المدة',
        absence_policy: 'سياسة الغياب',
        shift: 'شفت',
        shift2: 'التحول الجديد',
        fill_in_user: 'مستخدم آخر',
        message: 'رسالة',
        current_authorization_user: 'مستخدم التفويض الحالي',
        approvals_display: 'الموافقات',
    },
    months: {
        january: 'يناير',
        february: 'فبراير',
        march: 'مارس',
        april: 'ابريل',
        may: 'مايو',
        june: 'يونيو',
        july: 'يوليو',
        august: 'أغسطس',
        september: 'سبتمبر',
        october: 'أكتوبر',
        november: 'نوفمبر',
        december: 'ديسمبر',
    },
    sortFields: {
        employee_number: '# الموظف',
        full_name: 'الاسم الكامل',
        type: 'نوع الطلب',
        date_stamp1: 'تاريخ',
        apply: 'تطبيق',
        choose_field: 'اختيار المجال',
        sort_by: 'صنف حسب',
        request_details: 'طلب تفاصيل',
        decline: 'انخفاض',
        approve: 'يوافق',
        new_request: 'طلب جديد',
        reset: 'إعادة تعيين',
    },
    users: {
        employee_number : '#',
        full_name: 'الاسم الكامل',
        work_email: 'البريد الإلكتروني',
        title: 'المسمى الوظيفي',
        status: 'المتاحة اليوم',
        work_phone: 'هاتف عمل',
        mobile_phone: 'رقم الهاتف المحمول',
        time_stamp: 'لكمة في الوقت المناسب',
        users: 'المستخدمين',
        find_employee: 'العثور على موظف',
        total: 'مجموع',
        leave_type: 'نوع الإجازة',
        full_arabic_name: 'الاسم العربي الكامل'
    },
    articles: {
        of: 'من',
        in: 'في'
    },
    team: {
        total_team_members: 'مجموع أعضاء الفريق',
        total_attendance_today: 'إجمالي الحضور اليوم',
        request_authtorizations: 'طلب التراخيص',
        employees_on_vacation: 'الموظفين في إجازة',
        exused_leaves_today: 'الأوراق المعذرة اليوم',
        absent_employees_today: 'تغيب الموظفين اليوم'
    },
    home: {
        company_announcement: 'إعلانات الشركة',
        birthday: 'عيد ميلاد',
        find_news: 'البحث عن الأخبار',
        today_is: 'اليوم هو',
        new_members: 'أعضاء جدد',
        welcome_new_employee: 'مرحبا بكم موظف جديد'
    },
    settings: {
        en: "الإنجليزية",
        ar: 'عربى',
        lang: 'لغة',
        change_lang: 'تغيير اللغة الافتراضية',
        system_settings: 'اعدادات النظام',
    },
    week: {
        mon: 'الإثنين',
        tue: 'الثلاثاء',
        wed: 'الأربعاء',
        thu: 'الخميس',
        fri: 'يوم الجمعة',
        sat: 'يوم السبت',
        sun: 'الأحد'
    },
     company: {
        division: 'قطاع',
        department: 'قسم',
        contact_info: 'معلومات الاتصال',
        search: 'البحث عن قسم أو قسم'
    }
};

export default ar;