const en = {
    global: {
        default_view: 'Deault view',
        loading: 'Loading',
        print: 'Print',
        export: 'Export',
        actual_punches: 'Actual Punches',
        schedules: 'Schedules',
        attendance: 'Attendance',
        employees: 'Employees',
        report: 'Report',
        my_account: 'My account',
        help: 'Help',
        schedule: 'Schedule',
        authorization: 'Authorization',
        logout: 'Logout',
        new: "New",
        view: 'View',
        send: "Send",
        cancel: 'Cancel',
        cancel_request: 'Cancel Request',
        authtorize: 'Authtorize',
        decline: 'Decline',
        home: 'Home',
        team: 'Team',
        company: 'Company',
        me: 'Me',
        settings: 'Settings',
        policies: 'Policies',
        departments: 'Departments',
        about: 'About Earthlink',
        back: 'Back',
        punch_in_out: 'Punch In / Out',
        new_request: 'New Request',
        pending_requests: 'Pending Requests',
        notifications: 'Notifications',
        user_requests: 'Pending Requests by User',
        make_request_as_user: 'Make Request as User',
        email: 'E-mail',
        work_phone: 'Work phone',
        available_today: 'Available today',
        mobile_number: 'Mobile number',
        not_provided: 'Not provided',
        user_id: 'User ID',
        hire_date: 'Hire Date',
        section: 'Section',
        department: 'Department',
        length_of_service: 'Length of service',
        available_balance: 'Available balance',
        available_balance_types: '(Hourly, Annual, Flexible Leaves)',
        extra_information: 'Extra information',
        reset: 'Reset',
        today: 'Today',
        selected_date: 'Selected Date',
        errors_codes: 'Errors-Codes',
        in: 'In',
        out: 'Out',
        vacation: 'Vacation',
        leaves: 'Leaves',
        absence: 'Absence',
        exceptions: 'Exceptions',
        attendance_kpis: 'Attendance KPIs',
        working_hours: 'Working Hours',
        excuse_leaves: 'Excuse Leaves',
        absence_days: 'Absence Days',
        from: 'From',
        to: 'To',
        vacations: 'Vacations',
        subordinates: 'Subordinates',
        employee: 'Employee',
        full_name: "Full Name",
        job_title: 'Job title',
        displaying: 'Displaying',
        total: 'total',
        view_profile: 'View Profile',
        no_results: 'Sorry, no results for',
        try_different_keywords: 'Try different keywords',
        find_request: 'Find request',
        selected_from: "Selected from",  
        select_first_date: 'Please select the first day',
        select_last_date: 'Please select the last day',
        show_processed_data: 'Show Processed data for',
        users_in_total: 'users in total',
        success: 'Success!',
        process_failed: 'Process failed!',
        show_more: 'Show more',
        my_pending_requests: 'My Pending Requests',
        edit: 'Edit',
        requests: 'Requests',
        basic_info: 'Basic info',
        save: 'Save',
        account_info: 'Account info',
        full_arabic_name: 'Full arabic name',
        hour: 'hour',
        hours: 'hours',
        days: 'days',
        day: 'day',
        minute: 'minute',
        minutes: 'minutes',
        years: 'years',
        previous: 'Previous',
        next: 'Next',
        time: 'Time',
        date: 'Date',
        punch_type: 'Punch type',
        in_out: 'In / Out',
        leave_type: 'Leave Type',
        online: 'Online',
        offline: 'Offline',
        month_view: 'Month view',
        week_view: 'Week view',
        day_view: 'Day view',
        about_elteam: 'About Earthlink',
        hierarchy: 'Hierarchy',
        elteam_journal: 'Earthlink journal',
        blog: 'Blog',
        internal_vacancies: 'Internal vacancies',
        company_hierarchy: 'Company - Hierarchy',
    },
    dropdown: {
        employee_number: 'Employee#',
        full_arabic_name: 'Full Arabic Name',
        default_department: 'Department',
        status: 'Status',
        full_name: 'Full Name',
        report_to_user: 'Report to User',
        work_phone: 'Work phone',
        work_email: 'Work email',
        any: 'Any',
        name: 'Name',
        type: 'Type',
        date_stamp1: 'Date',
        duration: 'Duration',
        absence_policy: 'Absence Policy',
        shift: 'Shift',
        shift2: 'New Shift', 
    },
    actual_punches: {
        pageTitle: 'Actual Punches',
    },
    recurring_templates: {
        pageTitle: 'Recurring Templates',
    },
    recurring_schedules: {
        pageTitle: 'Recurring Shedules',
    },
    accrual_balances: {
        pageTitle: 'Accrual Balances',
        first_name: 'First Name',
        last_name: 'Last Name',
        accrual_policy_account: 'Accrual account',
        balance: 'Balance',
        default_department: 'Department'
    },
    timesheet: {
        pageTitle: 'TimeSheet',
        employee: 'Employee',
        in: 'In',
        out: 'Out',
        request: 'Request',
        exceptions: 'Exceptions',
        total_time: 'Total time',
        worked_time: 'Worked time',
        regular_time: 'Regular time',
        statutory_holiday: 'Statutory holiday',
        hourly_leave_balance: 'Hourly Leave Balance',
        vacation_unpaid: 'Vacation (unpaid)',
        vacation_paid: 'Vacation (paid)',
        hourly_leave_balance_withdrawal: 'Hourly Leave Balance (Withdrawal)',
        accumulated_time: 'Accumulated Time',
        absence: 'Absence',
        week: 'Week',
        pay_period: 'Pay period',
        employee_number: 'Employee#',
        full_arabic_name: 'Full Arabic Name',
        default_department: 'Department',
        status: 'Status',
        full_name: 'Full Name',
        report_to_user: 'Report to User',
        vacation: 'Vacation',
        branch: 'Branch',
        no_branch: 'No branch',
        hq4: 'HQ4',
        department: 'Department',
        software_research_and_development: 'Software research and development',
        no_department: 'No department',
        hourly_leave_paid: 'Hourly Leave Paid',
        work_phone: 'Work phone',
        work_email: 'Work email',
        employees: 'Employees',
    },
    exceptions: {
        pageTitle: 'Exceptions',
        first_name: 'First name',
        last_name: 'Last name',
        date_stamp: 'Date',
        severity: 'Severity',
        exception_policy_type: 'Exception',
        exception_policy_type_id: 'Code',
        shift_type: 'Shift type',
        time_difference: 'Time difference',
        title: 'Title',
        group: 'Group',
        default_branch: 'Default Branch',
        default_department: 'Default Department',
        branch: 'Branch',
        department: 'Department',
        country: 'Country',
        province: 'Province',
        policy_group: 'Policy Group',
        permission_group: 'Permission Group',
        pay_period_schedule: 'Pay Period Schedule',
        created_by: 'Created By',
        created_date: 'Created Date',
        updated_by: 'Updated By',
        updated_date: 'Updated Date'
    },
    tabs: {
        basic_search: 'Basic search',
        advanced_search: 'Advanced search',
        saved_search: 'Saved search'
    },
    schedules: {
        pageTitle: 'Schedules'
    },
    punches: {
        pageTitle: 'Punches'
    },
    accrual_schedule: {
        pageTitle: 'Accrual Schedule'
    },
    custom_schedules: {
        pageTitle: 'Custom Schedules'
    },
    requests: {
        pageTitle: 'Requests',
        employee_number: "Employee",
        full_name: 'Full Name',
        type: 'Type',
        status: 'Status',
        date_stamp1: 'DateTime',
        date_stamp: 'DateTime',
        duration: "Duration",
        absence_policy: "Absence Policy",
        shift: 'Shift',
        shift2: 'New Shift',
        fill_in_user: 'Other user',
        message: 'Message',
        current_authorization_user: 'Current Authorization User',
        approvals_display: 'Approvals',
        created_date: 'Created Date',
        employee: 'Employee',
        start_date: 'Start Date',
        end_date: 'End Date',
        created_by: 'Created By',
        updated_by: 'Updated By',
        other_user: 'Other User',
        clear_search: 'Clear Search',
        search: 'Search',
        request_type: 'Request Type',
        apply_for: 'Apply For',
        direct_manager: 'Direct Manager',
        date_from: 'Date From',
        reason_message: 'Reason / Message',
        date_to: 'Date To',
        new_request: 'New Request',
        punch_status: 'Punch Status',
        punch_date: 'Punch Date',
        punch_time: 'Punch Time',
        date: 'Date',
        start_time: 'Start Time',
        end_time: 'End Time',
        users: 'Users',
        schedule: 'Schedule',
        another_employee: 'Another Employee',
        off_day: 'Off day',
        punch_in_time: 'Punch In Time',
        punch_out_time: 'Punch Out Time',
        ticket_id: 'Ticket ID',
        approvals: 'Approvals',
        job_location: 'Job Location',
        request: 'Request',
        authorization_history: 'Authorization History',
        authorized: 'Authorized',
        employee_shift: 'Employee Shift',
        cancel: 'Cancel',
        send: 'Send',
        request_sent: 'Your new request has been sent',
        request_failed: 'Your request is failed unsuccesfully',
        approved: 'Approved',
        approved_message: 'Request has been approved',
        declined: 'Declined',
        declined_message: 'Request has been declined',
        failed: 'Process failed',
        failed_message: 'Your request is failed unsuccesfully'
    },
    messages: {
        pageTitle: 'Messages'
    },
    preferences: {
        pageTitle: 'Preferences'
    },
    request_authorizations: {
        pageTitle: 'Request(Authorizations)'
    },
    logout: {
        pageTitle: 'Logout'
    },
    errors: {
        no_results_found: 'No Results Found',
        request_not_canceled: 'Request Not Canceled',
        server_error: 'Server error',
        no_birthday: 'No new birthdays',
        no_new_members: 'No new members',
        not_permissions: 'Not permissions'
    },
    authRequests: {
        employee_number: 'Employee',
        full_name: 'Full Name',
        type: 'Type',
        status: 'Status',
        date_stamp1: 'Date time',
        duration: 'Duration',
        absence_policy: 'Absence Policy',
        shift: 'Shift',
        shift2: 'New shift',
        fill_in_user: 'Other user',
        message: 'Message',
        current_authorization_user: 'Current Authorization User',
        approvals_display: 'Approvals',
        
    },
    months: {
        january: 'January',
        february: 'February',
        march: 'March',
        april: 'April',
        may: 'May',
        june: 'June',
        july: 'July',
        august: 'August',
        september: 'September',
        october: 'October',
        november: 'November',
        december: 'December',
    },
    sortFields: {
        employee_number: 'Employee #',
        full_name: 'Full Name',
        type: 'Request Type',
        date_stamp1: 'Date',
        apply: 'Apply',
        choose_field: 'Choose a field',
        sort_by: 'Sort By',
        request_details: 'Request Details',
        decline: 'Decline',
        approve: 'Approve',
        new_request: 'New Request',
        reset: 'Reset'
    },
    articles: {
        of: 'of',
        in: 'in'
    },
    users: {
        employee_number : '#',
        full_name: 'Full name',
        work_email: 'E-mail',
        title: 'Job title',
        status: 'Available today',
        work_phone: 'Work phone',
        mobile_phone: 'Mobile number',
        time_stamp: 'Punch in time',
        users: 'Users',
        find_employee: 'Find employee',
        total: 'total',
        start_date: 'Date',
        leave_type: 'Leave type',
        full_arabic_name: 'Full arabic name'
    },
    team: {
        total_team_members: 'Total team members',
        total_attendance_today: 'Total attendance today',
        request_authtorizations: 'Request authorizations',
        employees_on_vacation: 'Employees on vacation',
        exused_leaves_today: 'Exused leaves today',
        absent_employees_today: 'Absent employees today'

    },
    home: {
        company_announcement: 'Company`s announcements',
        birthday: 'Birthday',
        find_news: 'Find news',
        today_is: 'Today is',
        new_members: 'New members',
        welcome_new_employee: 'Welcome a new employee'
    },
    settings: {
        en: "english",
        ar: 'arabic',
        lang: 'language',
        change_lang: 'Change default language',
        system_settings: 'System Settings',
    },
    week: {
        mon: 'Monday',
        tue: 'Tuesday',
        wed: 'Wednesday',
        thu: 'Thursday',
        fri: 'Friday',
        sat: 'Saturday',
        sun: 'Sunday'
    },
    company: {
        division: 'Division',
        department: 'Department',
        contact_info: 'Contact info',
        search: 'Find division or department'
    }
};

export default en;

